# see https://arduino.github.io/arduino-cli/1.0/library-specification/#library-metadata

name=modbus_rtu_cpp
version=1.0.0
author=GJW
maintainer=gjwmotor <github.com/gjwmotor>
sentence=Modbus-RTU library for Arduino and ESP32
paragraph=This library is Modbus-Rtu protocol
category=Other
url=https://github.com/gjwmotor/modbus_rtu_cpp
architectures=*
